workflows:
  ios-workflow:
    name: Build iOS app
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.mondomaine.lejeuneperefils"
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_KEY
        key_id: 3HP8J62754
        issuer_id: 46d4a030-cbad-4ff9-a8e9-8e15b157646b
        submit_to_testflight: true
