workflows:
  ios-workflow:
    name: Build iOS app
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.mondomaine.lejeuneperefils"
        APP_STORE_CONNECT_KEY: |
          -----BEGIN PRIVATE KEY-----
          (ton contenu de clé privée ici)
          -----END PRIVATE KEY-----
        APP_STORE_CONNECT_KEY_ID: ZV8WH5HF9X
        APP_STORE_CONNECT_ISSUER_ID: 46d4a030-cbad-4ff9-a8e9-8e15b157646b
    triggering:
      events:
        - push
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS release
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
    publishing:
      app_store_connect:
        api_key: APP_STORE_CONNECT_KEY
        key_id: APP_STORE_CONNECT_KEY_ID
        issuer_id: APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
