workflows:
  ios-workflow:
    name: Build iOS app
    variable_groups:
      - app_store_credentials # ✅ C'est le seul groupe dont vous avez besoin
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.mondomaine.lejeuneperefils"
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
